--create tb_account
DROP TABLE IF EXISTS TB_ACCOUNT;
CREATE TABLE TB_ACCOUNT(
USER_ID VARCHAR(10),
USER_NAME VARCHAR(50),
PWD VARCHAR(50),
PHONE VARCHAR(11),
EMAIL VARCHAR(50),
ROLE_ID VARCHAR(10),
IND_STATUS VARCHAR(1),
CONSTRAINT pk_userId PRIMARY KEY (USER_ID)
);
--create tb_sequence
DROP TABLE IF EXISTS TB_SEQUENCE;
CREATE TABLE TB_SEQUENCE(
SEQ_NAME VARCHAR(50),
INIT_VALUE VARCHAR(10),
MAX_VALUE VARCHAR(10),
CURR_VALUE VARCHAR(10),
STEP VARCHAR(10),
IND_STATUS VARCHAR(1),
CONSTRAINT pk_seqName PRIMARY KEY (SEQ_NAME)
);
--create tb_role
DROP TABLE IF EXISTS TB_ROLE;
CREATE TABLE TB_ROLE(
ROLE_ID VARCHAR(10),
ROLE_NAME VARCHAR(50),
IND_STATUS VARCHAR(1),
CONSTRAINT pk_roleId PRIMARY KEY (ROLE_ID)
);
--create tb_permission
DROP TABLE IF EXISTS TB_PERMISSION;
CREATE TABLE TB_PERMISSION(
ROLE_ID VARCHAR(10),
MENUS VARCHAR(1000),
IND_STATUS VARCHAR(1),
CONSTRAINT pk_roleId PRIMARY KEY (ROLE_ID)
);
--create tb_menu
DROP TABLE IF EXISTS TB_MENU;
CREATE TABLE TB_MENU(
MENU_ID VARCHAR(10),
MENU_NAME VARCHAR(50),
PARENT_MENU_ID VARCHAR(10),
IND_STATUS VARCHAR(1),
CONSTRAINT pk_menuId PRIMARY KEY (MENU_ID)
);